#!/usr/bin/env python3
# Description: Regenerate the README repository structure section from top-of-file descriptions.

from __future__ import annotations

import re
import subprocess
from pathlib import Path


README = "README.md"
START = "<!-- BEGIN AUTO-GENERATED REPO STRUCTURE -->"
END = "<!-- END AUTO-GENERATED REPO STRUCTURE -->"
DESCRIPTION_RE = re.compile(r"^\s*(?:#|//|;|<!--)\s*Description:\s*(.*?)\s*(?:-->)?\s*$")
SKIP_DIRS = {".git", ".vscode", "__pycache__"}
PINNED_TOP_LEVEL_DIRS = ("examples", "scripts")
PINNED_TOP_LEVEL_RANKS = {name: rank for rank, name in enumerate(PINNED_TOP_LEVEL_DIRS)}


def repo_root() -> Path:
    return Path(__file__).resolve().parents[1]


def tracked_files(root: Path) -> list[Path]:
    try:
        result = subprocess.run(
            ["git", "ls-files"],
            cwd=root,
            check=True,
            text=True,
            capture_output=True,
        )
    except (subprocess.CalledProcessError, FileNotFoundError):
        return sorted(
            path.relative_to(root)
            for path in root.rglob("*")
            if path.is_file()
            and len(path.relative_to(root).parts) > 1
            and not any(part in SKIP_DIRS for part in path.relative_to(root).parts)
        )

    paths = [Path(line) for line in result.stdout.splitlines() if line.strip() and len(Path(line).parts) > 1]
    script_path = Path(__file__).resolve().relative_to(root)
    if script_path not in paths:
        paths.append(script_path)
    return sorted(paths)


def description_for(path: Path) -> str:
    full_path = repo_root() / path
    try:
        lines = full_path.read_text(encoding="utf-8").splitlines()
    except UnicodeDecodeError:
        return ""

    for line in lines[:30]:
        match = DESCRIPTION_RE.match(line)
        if match:
            return match.group(1).strip()
        stripped = line.strip()
        if stripped and not stripped.startswith(("#!", "#$", "#", "//", ";", "<!--")):
            break

    return ""


def directory_entries(files: list[Path]) -> list[tuple[Path, bool]]:
    dirs = {Path(part) for file_path in files for part in file_path.parents if str(part) != "."}
    entries = [(path, True) for path in dirs]
    entries.extend((path, False) for path in files)
    return sorted(entries, key=entry_sort_key)


def entry_sort_key(entry: tuple[Path, bool]) -> tuple[int, str, tuple[str, ...], bool]:
    path, is_dir = entry
    top_level_name = path.parts[0]
    top_level_rank = PINNED_TOP_LEVEL_RANKS.get(top_level_name, len(PINNED_TOP_LEVEL_RANKS))
    top_level_sort_name = "" if top_level_name in PINNED_TOP_LEVEL_RANKS else top_level_name
    return top_level_rank, top_level_sort_name, path.parts, not is_dir


def generated_section(files: list[Path]) -> str:
    lines = [
        "## Repository Structure",
        START,
        "",
        "_This section is generated by `scripts/update-readme-directory.py`._",
        "",
    ]

    for path, is_dir in directory_entries(files):
        depth = len(path.parts) - 1
        indent = "  " * depth
        if is_dir:
            lines.append(f"{indent}- `{path}/`")
        else:
            desc = description_for(path)
            path = str(path).split("/")[-1]
            if desc:
                lines.append(f"{indent}- `{path}` - {desc}")
            else:
                lines.append(f"{indent}- `{path}`")

    lines.extend(["", END, ""])
    return "\n".join(lines)


def update_readme(root: Path, section: str) -> None:
    readme_path = root / README
    readme = readme_path.read_text(encoding="utf-8").rstrip()

    if START in readme and END in readme:
        pattern = re.compile(rf"\n*## Repository Structure\n{re.escape(START)}.*?{re.escape(END)}", re.S)
        readme = pattern.sub("\n\n" + section.rstrip(), readme)
    else:
        readme = readme + "\n\n" + section.rstrip()

    readme_path.write_text(readme + "\n", encoding="utf-8")


def main() -> None:
    root = repo_root()
    files = tracked_files(root)
    update_readme(root, generated_section(files))


if __name__ == "__main__":
    main()
